networks:
  starcraft-network:
    driver: bridge

services:
  app:
    build:
      context: .
    container_name: starcraft-app
    volumes:
      - .:/app
    environment:
      APP_ENV: ${APP_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    depends_on:
      - db
    tty: true  # Keeps container open for interaction
    command: ["bash"]
    networks:
      - starcraft-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s        # Check every 10 seconds
      timeout: 5s          # Timeout after 5 seconds
      retries: 5           # Retry up to 5 times before considering unhealthy

  db:
    image: postgres:13
    container_name: starcraft-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starcraft_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - starcraft-network

volumes:
  postgres_data:

