name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install flake8 black
      - name: Run Linter
        run: |
          black --check .
          flake8

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Services
        run: docker-compose up --build -d
      - name: Run Tests
        run: docker exec -it starcraft-app pytest --cov=.

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

